<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vr</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)(for|if|do|dow|dou|select|begsr|BegFunc|BegSr|BegConstructor|BegClass|Try)</string>
	<key>foldingStopMarker</key>
	<string>(?i)(endfor|endif|enddo|endsl|endsr|endFunc|endSr|endConstructor|endClass|EndTry)</string>
	<key>grammaurl</key>
	<string>http://manual.macromates.com/en/language_grammars#language_grammars</string>
	<key>name</key>
	<string>vr vr</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i)\b(ctl-opt)\b</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.other.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(exec sql)\b</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>string.quoted.single.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(c/EXEC SQL)\b</string>
			<key>end</key>
			<string>(?i)\b(c/END-EXEC)\b</string>
			<key>name</key>
			<string>string.quoted.single.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(begsr|Do|DoWhile|DoUntil|for|ForEach|if|select|endsr|endif|endsl|enddo|endfor|With|EndWith)\b</string>
			<key>name</key>
			<string>keyword.control.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(try|catch|endtry)\b</string>
			<key>name</key>
			<string>keyword.control.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(when|exsr|else|elseif|other)\b</string>
			<key>name</key>
			<string>keyword.control.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[\%](abs|addr|alloc|bitand|bitnot|bitor|bitxor|char|check|checkr|date|days|dec|dech|decpos|diff|div|editc|editflt|editw|elem|eof|equal|error|fields|float|found|graph|hours|int|inth|kds|len|lookup|minutes|months|mseconds|nullind|occur|open|paddr|paddr|parms|realloc|rem|replace|subst|scan|seconds|shtdn|size|sqrt|status|str|str|str|subdt|this|time|timestamp|tlookup|trim|triml|trimr|ucs2|uns|unsh|xfoot|xlate|years)\b</string>
			<key>name</key>
			<string>constant.language.figurative.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(acq|add|adddur|alloc|call|callb|callp|cas|case|caseq|casge|casgt|casle|caslt|casne|cat|chain|check|checkr|clear|close|commit|comp|dealloc|define|delete|div|dsply|dump|endcs|Event|except|Extends|exfmt|exsr|extrct|feod|force|goto|in|ITERATE|Key|kfld|klist|Len|leave|leavesr|Like|lookup|mhhzo|mhlzo|mlhzo|mllzo|mvr|next|not|occur|on|open|other|out|Partial|post|read|readc|reade|readp|realloc|rel|reset|return|rolbk|scan|setgt|setll|setoff|seton|shtdn|Shared|sorta|sqrt|sub|subdur|tag|test|testb|testn|testz|time|unlock|update|write|xfoot|xlate)\b</string>
			<key>name</key>
			<string>variable.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(var)\b</string>
			<key>name</key>
			<string>storage.type.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(type|BegClass|BegFunc|BegConstructor|DclDB|DBName|DclDiskFile|DclMemoryFile|EndConstructor|EndClass|EndFunc|BegSr|EndSr|DclNamespace|Using|Access))\b</string>
			<key>name</key>
			<string>storage.type.vr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>simple numerics in () and []</string>
			<key>match</key>
			<string>(?&lt;=(\(|\[))((\-\+)*[0-9 ,\.\+\-\*\/]+)(?=(\)|\]))</string>
			<key>name</key>
			<string>constant.numeric.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[*](And|BASE|ENTRY|ALL|BLANK|BLANKS|Boolean|Dft|End|eq|FALSE|HIVAL|Hourglass|Input|Indexed|Integer2|Integer4|LOVAL|ne|NEW|No|NOTHING|Not|Object|ON|OFF|or|Public|private|Protected|Start|String|TRUE|THIS|USRCTL|yes|ZERO|ZEROS)\b</string>
			<key>name</key>
			<string>constant.language.vr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(\-|\+)?((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?(?=\s|\.|,|\))</string>
			<key>name</key>
			<string>constant.numeric.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\%\&gt;</string>
			<key>end</key>
			<string>\&lt;\%</string>
			<key>name</key>
			<string>storage.type.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^[ \t]{0,5}[ hfdc][*]</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.block.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\/</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.block.vr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable previx reserved word</string>
			<key>match</key>
			<string>\b(?i:(DclSrParm|Dclfld))\b</string>
			<key>name</key>
			<string>storage.modifier.vr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.vr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.vr</string>
				</dict>
			</array>
		</dict>

		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.single.vr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.vr</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.vr</string>
	<key>uuid</key>
	<string>f43aff62-4f12-4328-9cbb-a8a7a3f1cfef</string>
</dict>
</plist>
